= Resumen Unidad 1
Jaime Andrés Cortina Rangel #17100196

=== Modelo de caja
El modelo de caja se utiliza en el css y sirve para definir las 4 partes que conforman una caja en una página web. + 

=== Content, Padding, Border, Margin y Outline
- La parte central e interna, es el **content* y aquí reside el contenido real a utilizar y mostrar en la página, como texto e imágenes.
- La segunda parte externa al *content*, es el *padding*, y por así decirlo "limpia" el área al rededor del contenido*, por lo tanto es transparente.
- El *border* es la linea que rodea al *content*, y dependiendo del *padding* estará más o menos cerca del *content*. Se le puede definir el grosor.
- El *margin* es como el *padding* es al *content*, sirve para "limpiar" el area por fuera del *border*, e igualmente es transparente.
- El *outline* es un tanto gráfico solamente, sirve como decoracion para que el *border* tenga una ligera aura, que los rodea.

=== Propiedades 

==== *Display*
- *Box:* Sirve para delimitar todo un párrafo.
- *Inline:* Para ésta propiedad el elemento inline estándar es el span, sirve para poner texto dentro de un parrafo sin afectar el flujo o interrumpirlo. Se selecciona por cada linea del párrafo, individualmente.
- *Inline-Box:* Se obtiene un comportamiento mezclado entre el *box* y el *inline*. Básicamente es tener un inline dentro de todo un párrafo que es *box*.
- *None:* Sirve para ocultar elementos que no se quieren mostrar, sin necesidad de eliminarlos o dañarlos.

==== Box Sizing
- *content-box:* Solamente incluye el alto y el ancho de el contenido, sin tomar en cuenta el *padding* y el *border*, del modelo de cajas (no se modifican).
- *border-box:* Se incluye el *padding* y el *border* para el alto y el ancho, a diferencia del *content-box*

=== Flujo de documento
Es la forma en la que se muestran, ordenan o despliegan los elementos en la página web, dependiendo del tipo de elemento.

=== Tipos de posicionamiento
Por default, los elementos tendrán la posición *static*, y para quitar o modificar su valor en su posicion usaremos los *tipos de posicionamiento*.
- *Relative:* Donde está posicionado originalmente, será su posicion definida.
- *Absolute:* Se basará con su padre directo, y no tendrá una posicion definida.
- *Fixed:* El navegador le dará el punto de referencia.
- *Sticky:* Este es normal la posicion original, pero al llegar a cierto punto se modifica cambiando a fixed.

=== Unidades de medida en CSS

==== Absolutas
Son las medidas que utilizamos cotidianamente en la vida real, y que nunca varian. (Centímetros, milimetros y pulgadas)

==== Relativas
- *px:* indica la medida en pixeles
- *%:* indica el porcentaje respectivo al padre
- *em:* Tamaño de la fuente
- *rem:* Tamaño de la fuente raíz
- *ex:* Aproximadamente la mitad del tamaño fuente (altura letra x)
- *ch:* El ancho del caractér cero

=== Selectores Básicos
- Selector universal, se representa con un asterisco y selecciona todos los elementos.
- De etiqueta, se represena con una h seguida de un numero y selecciona todas las etiquetas.
- De identificador, se representa con una palabra, anteponiendo un #, se aplica solo a elementos que lo contengan.
- De clase, se representa con un elemento, seguido de un punto y la clase definida, se aplica a elementos que tengan la clase.

=== Selectores Relacionales
- *div p*, selecciona todos los elementos p que estén dentro de Div.
- *div > p*, selecciona a todos los elementos p  hijos directos de div.
- *div + p*, selecciona el elemento p que sea hermano, y esté justo al lado del Div.
- **div ~ p*, todos los elementos p que sean hermanos de Div.

=== PseudoSelectores
Se dividen en Pseudoclases y Pseudoelementos, y son llaves o claves que se agregan a los selectore. Indica los estados que puede llegar a tener.

=== PseudoClases
Se agregan por el mismo navegador, de acuerdo al estado en el que se encuentren los elementos.

=== PseudoElementos
Solamente indican una parte determinada de un elemento.

=== Cascada
Se utiliza cuando se entra en conflicto los elementos con sus declaraciones en el css o en la estructura, distintos parametros tienen cierta importancia, se muestra a continuacion:
.Table Title
|===
|Factor |Descripción
|1.Importancia
|El origen de en donde esta ubicado el estilo
|2.Especificidad
|El peso o que tan específico es
|3.Orden
|La ultima regla escrita en el código es la que gana, y sobre escribe a la anterior
|===

=== Especificidad
Cuando se entra en conflicto, se tiene que definir el peso de los selectore, y gana quien mas peso tenga, o sea más específico. A continuacion una tabla de cómo se calcula:
.Table Title
|===
|Jerarquía |Selector|Especificidad
|4
|Etiqueta HTML
|1,0,0,0 puntos
|3
|ID
|0,1,0,0 puntos
|2
|Clase, pseudoclase,  atributo
|0,0,1,0 puntos
|1
|Elemento, pseudoelemento
|0,0,0,1 puntos
|0
|Selector universal *
|0,0,0,0 puntos
|===

TIP: Cabe destacar que el important! es el mas importante de todos, y es el que mas peso de todos tiene.